### ISSUE TITLE
Broken - UTF8 error

### ISSUE THREAD

**Issue by STashakkori** [LaBatata101/grep_bin#1]
Regardless of what binary I pass to the tool I get the following error:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }', src/utils.rs:41:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by STashakkori** [comment]
Seems to work for ASCII text files:

./grep_bin test123.txt "Here"
test123.txt
00000000:  48 65 72 65           Here

The tool description says: "Search a sequence of bytes in a binary file". Currently doesn't seem to be the case

**Comment by LaBatata101** [comment]
Are you passing the byte sequence inside quotes?

**Comment by LaBatata101** [comment]
Does this issue still occur in the current version(1.0.1)? I wasn't able to reproduce.

**Comment by STashakkori** [comment]
Yes the behavior I am seeing is in version 1.0.1. I posted a response to an issue that was closed so I will link them here. With apologies:

https://github.com/LaBatata101/grep_bin/issues/2#issuecomment-961542404

https://github.com/LaBatata101/grep_bin/issues/2#issuecomment-961543463

Please see the behavior. I think I am narrowing in a bit on the issue
