### ISSUE TITLE
Broken - Usage doesn't match documentation

### ISSUE THREAD

**Issue by STashakkori** [LaBatata101/grep_bin#2]
Hello again. When I run using the usage you show in your documentation, the tool prints the usage:

So running this:
grep_bin -f test.bin -b fffe

Gives this:
error: Found argument '-b' which wasn't expected, or isn't valid in this context

USAGE:
    grep_bin <FILE>... <PATTERN> -f <filetype>...

For more information try --help

**Comment by STashakkori** [comment]
Running with ascii string option gives a similar error:

./grep_bin -f test.bin -s "Hello World"
error: Found argument '-s' which wasn't expected, or isn't valid in this context

USAGE:
    grep_bin <FILE>... <PATTERN> -f <filetype>...

For more information try --help

**Comment by LaBatata101** [comment]
I've changed the way of how the program receives input but forgot to update the docs, sorry about that!

This is how it works now `grep_bin [OPTIONS] <FILE>... <PATTERN>`,  pattern can be an ascii string or one of the following types of hex strings(f9b4ca, F9B4CA, f9B4Ca)

**Comment by STashakkori** [comment]
Ok I think I see the problem. The new tool seems to work with many byte patterns. However does not work with ff

ff makes it panic for some reason. I will look to see what other patterns crash it

**Comment by STashakkori** [comment]
Oh interesting. It seems to depend on what binary it is parsing. If you run it on the binary grep_bin binary itself, you will be able to reproduce my error. 

Panics:
./grep_bin target/debug/grep_bin ff00

Panics:
./grep_bin target/debug/grep_bin ff

Does not panic:
./grep_bin target/debug/grep_bin 00

11 works fine. But ah I think we're onto something here. Try running it with 22
./grep_bin target/debug/grep_bin 22
Output:
00001298:  22 			"
00001441:  22 			"
000014E9:  22 			"
00001639:  22 			"
000017A1:  22 			"
00001E50:  22 			"
00000849:  22 			"
00000861:  22 			"
00000879:  22 			"
00001020:  22 			"
00001158:  22 			"
00001668:  22 			"
00001938:  22 			"
00001B80:  22 			"
00001F20:  22 			"
