### ISSUE TITLE
Cargo install version doesn't color all matches

### ISSUE THREAD

**Issue by STashakkori** [LaBatata101/grep_bin#3]
When I run the cargo installed version, which on the surface seems to work as intended, I notice that it is not coloring every byte that matches my pattern. It seems to color every other byte that it finds that matches for the most part, but not exactly that behavior. 

For example when I search for FF I see this, where bold are the colored finds:

02532170:  00 D2 7F 43 00 00 00 00  00 DB **_7F_** 43 00 00 00 00   |...C.......C....|
025321A0:  00 D2 **_7F_** 43 00 00 00 00  00 DB 7F 43 00 00 00 00   |...C.......C....|
025321A0:  00 D2 7F 43 00 00 00 00  00 DB **_7F_** 43 00 00 00 00   |...C.......C....|
025321D0:  00 DB **_7F_** 43 00 00 00 00  00 E4 7F 43 00 00 00 00   |...C.......C....|

Notice that it is not exactly every other time. Perhaps every other one per line? Or perhaps it only colors one finding per line and ignores the rest but obviously its not the first one it finds

**Comment by LaBatata101** [comment]
In the new [version](https://crates.io/crates/grep_bin) published to crates.io, this `hexdump` output style has replaced by a simpler one so the coloring issue is not a problem in this current version, but the `hexdump` output style will be added in an future version. I will close this issue now.

**Comment by STashakkori** [comment]
Ah. It's a shame because he hexdump is so beautiful. I look forward to the next version
